# -*- coding: utf-8 -*-
"""regression_model_comparison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_cJeej75x1LyhazypZ0dzbhKV4jwgLVu

Importing libraries
"""

import numpy as np
import pandas as pd
from sklearn.metrics import r2_score

"""Data preprocessing"""

dataset = pd.read_csv("job_salary_prediction_dataset.csv")
X = dataset[['job_title', 'experience_years', 'education_level',
             'skills_count', 'company_size', 'location']].values
y = dataset['salary'].values

print(X)

print(y)

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(
    transformers=[
        ('encoder', OneHotEncoder(sparse_output=False), [0, 2, 4, 5])
    ],
    remainder='passthrough'
)

X = ct.fit_transform(X)

print(X)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""Multiple Linear Regression"""

from sklearn.linear_model import LinearRegression
mult_lin_reg = LinearRegression()
mult_lin_reg.fit(X_train, y_train)

y_pred = mult_lin_reg.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test),1)),1))

mult_reg_score = r2_score(y_test, y_pred)
print(mult_reg_score)

"""Polynomial Linear Regression"""

from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures()
X_poly = poly_reg.fit_transform(X_train)

poly_lin_reg = LinearRegression()
poly_lin_reg.fit(X_poly, y_train)

y_pred = poly_lin_reg.predict(poly_reg.transform(X_test))
np.set_printoptions(precision = 2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test),1)),1))

poly_reg_score = r2_score(y_test, y_pred)
print(poly_reg_score)

"""Support Vector Regression"""

X_train_svr, X_test_svr, y_train_svr, y_test_svr = train_test_split(X, y, train_size=10000, random_state=42)

y_test_svr = y_test_svr.reshape(len(y_test_svr), 1)
y_train_svr = y_train_svr.reshape(len(y_train_svr), 1)

from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X_train_svr = sc_X.fit_transform(X_train_svr)
y_train_svr = sc_y.fit_transform(y_train_svr)

from sklearn.svm import SVR
svr_reg = SVR(kernel='rbf')
svr_reg.fit(X_train_svr, y_train_svr)

y_pred_svr = sc_y.inverse_transform(svr_reg.predict(sc_X.transform(X_test_svr)).reshape(-1,1))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_svr.reshape(len(y_pred_svr), 1), y_test_svr.reshape(len(y_test_svr),1)),1))

svr_score = r2_score(y_test_svr, y_pred_svr)
print(svr_score)

"""Decision Tree Regression"""

from sklearn.tree import DecisionTreeRegressor
dec_tree_reg = DecisionTreeRegressor()
dec_tree_reg.fit(X_train, y_train)

y_pred = dec_tree_reg.predict(X_test)
np.set_printoptions(precision = 2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test),1)),1))

dec_reg_score = r2_score(y_test, y_pred)
print(dec_reg_score)

"""Random Forest Regression"""

from sklearn.ensemble import RandomForestRegressor
rand_forest_reg = RandomForestRegressor(n_estimators=100, random_state=42)
rand_forest_reg.fit(X_train, y_train)

y_pred = rand_forest_reg.predict(X_test)
np.set_printoptions(precision = 2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test),1)),1))

rand_forest_score = r2_score(y_test, y_pred)
print(rand_forest_score)

"""Final Output"""

print("R2 Scores:")
print("Multiple Linear Regression: ", mult_reg_score)
print("Polynomial Regression: ", poly_reg_score)
print("Support Vector Regression(train size = 10000): ", svr_score)
print("Decision Tree Regression: ", dec_reg_score)
print("Random Forest Regression: ", rand_forest_score)
print("\n")

r2_scores = [mult_reg_score, poly_reg_score, svr_score, dec_reg_score, rand_forest_score]
models = ['Linear Regression', 'Polynomial Regression', 'SVR', 'Decision Tree', 'Random Forest']

best_score = max(r2_scores)
best_index = r2_scores.index(best_score)

print("Best Model:", models[best_index])
print("Best R2 Score:", best_score)